repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: nginx-ingress
    namespace: r2dlan-system
    chart: ingress-nginx/ingress-nginx
    version: 4.12.1
    createNamespace: true
    wait: true
    values:
      - controller:
          service:
            externalTrafficPolicy: Local
          ingressClassResource:
            default: true