repositories:
- name: jetstack
  url: https://charts.jetstack.io

releases:
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: v1.17.1
  hooks:
      - events: ["preapply"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - ./manifests/clusterissuer.yaml

      - events: ["preuninstall"]
        showlogs: true
        command: kubectl
        args:
          - delete
          - f
          - ./manifests/clusterissuer.yaml
