repositories:
- name: jetstack
  url: https://charts.jetstack.io

releases:
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: v1.17.1
  wait: true
  hooks:
      - events: ["presync"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - https://github.com/cert-manager/cert-manager/releases/download/v1.17.1/cert-manager.crds.yaml

      - events: ["postsync"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - ./manifests/clusterissuer.yaml

      # - events: ["preuninstall"]
      #   showlogs: true
      #   command: kubectl
      #   args:
      #     - delete
      #     - f
      #     - ./manifests/clusterissuer.yaml
