repositories:
- name: proprometheus-communitymetheus
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: prometheus-operator
  namespace: prometheus-operator
  chart: prometheus-community/kube-prometheus-stack
  version: 70.2.1
  values:
    - values.yaml