repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: prometheus-operator
  namespace: prometheus-operator
  chart: prometheus-community/kube-prometheus-stack
  version: 70.3.0
  createNamespace: true
  wait: true
  values:
    - crds:
        enabled: true
      defaultRules:
        rules:
          alertmanager: false
      alertmanager:
        enabled: false
      grafana:
        enabled: false
      prometheus:
        prometheusSpec:
          storageSpec:
            volumeClaimTemplate:
              spec:
                storageClassName: rook-ceph-block
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 10Gi
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-dns
          hosts:
            - prometheus.r2dlan.me
          tls:
            - secretName: prometheus-general-tls
              hosts:
                - prometheus.r2dlan.me
