repositories:
- name: rook-release
  url: https://charts.rook.io/release

releases:
  - name: rook-ceph
    namespace: rook-ceph
    chart: rook-release/rook-ceph
    version: v1.16.6
    createNamespace: true
    wait: true
    values:
      - crds:
          enabled: true
