repositories:
- name: uptime-kuma
  url: https://dirsigler.github.io/uptime-kuma-helm

releases:
- name: uptime-kuma
  namespace: uptime-kuma
  chart: uptime-kuma/uptime-kuma
  version: 2.21.2
  createNamespace: true
  wait: true
  values:
    - volume:
        enabled: true
        accessMode: ReadWriteOnce
        size: 4Gi
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-dns
        hosts:
          - host: uptime.r2dlan.me
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: uptime-tls
            hosts:
              - uptime.r2dlan.me
